[package]
name = "reddit_memes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
roux = "2.0.0"

tokio = { version = "1.19.2", features = ["rt-multi-thread", "macros"] }